 function ProfileForm({ profile, handleChange, handleSave }) {
    return (
        <form onSubmit={handleSave}>
            <label>
                Name:
                <input
                    type="text"
                    name="name"
                    value={profile.name}
                    onChange={handleChange}
                />
            </label>
            <label>
                Age:
                <input
                    type="number"
                    name="age"
                    value={profile.age}
                    onChange={handleChange}
                />
            </label>
            <label>
                Height:
                <input
                    type="number"
                    name="height"
                    value={profile.height}
                    onChange={handleChange}
                />
            </label>
            <label>
                Weight:
                <input
                    type="number"
                    name="weight"
                    value={profile.weight}
                    onChange={handleChange}
                />
            </label>
            <label>
                Goal:
                <input
                    type="text"
                    name="goal"
                    value={profile.goal}
                    onChange={handleChange}
                />
            </label>
            <button type="submit">Save</button>
        </form>
    );
}