export const workoutPlanStorageKey = 'fitness-flow-workout-plan'

export const exercises = [
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    group: 'Legs',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 8,
    description: 'A simple leg exercise that works your quads and glutes.',
    steps: [
      'Stand with your feet shoulder-width apart.',
      'Bend your knees and sit your hips back.',
      'Stand back up and squeeze your glutes.',
    ],
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    group: 'Legs',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 10,
    description: 'A lower body move that also helps with balance.',
    steps: [
      'Step one foot forward.',
      'Lower your back knee toward the floor.',
      'Push through the front foot and switch sides.',
    ],
  },
  {
    id: 'push-up',
    name: 'Push-up',
    group: 'Chest',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 7,
    description: 'A classic upper body exercise for chest, arms, and core.',
    steps: [
      'Start in a plank with hands under shoulders.',
      'Lower your chest toward the floor.',
      'Push back up while keeping your body straight.',
    ],
  },
  {
    id: 'row',
    name: 'Dumbbell Row',
    group: 'Back',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 8,
    description: 'A back exercise that also trains your arms.',
    steps: [
      'Place one hand on a bench or chair.',
      'Pull the dumbbell toward your ribs.',
      'Lower the dumbbell slowly and switch sides.',
    ],
  },
  {
    id: 'plank',
    name: 'Front Plank',
    group: 'Core',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 5,
    description: 'A core exercise that teaches you to stay tight and steady.',
    steps: [
      'Rest on your forearms and toes.',
      'Keep your hips level with your shoulders.',
      'Hold the position while breathing normally.',
    ],
  },
  {
    id: 'curl',
    name: 'Biceps Curl',
    group: 'Arms',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 6,
    description: 'A simple arm exercise for the front of your upper arms.',
    steps: [
      'Hold dumbbells at your sides.',
      'Curl the weights toward your shoulders.',
      'Lower them slowly without swinging.',
    ],
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    group: 'Cardio',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 6,
    description: 'A quick cardio exercise to warm up the whole body.',
    steps: [
      'Stand tall with your arms at your sides.',
      'Jump your feet out and raise your arms.',
      'Jump back to the starting position.',
    ],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    group: 'Cardio',
    equipment: 'Body Weight',
    level: 'Medium',
    minutes: 7,
    description: 'A faster exercise that mixes cardio and core work.',
    steps: [
      'Start in a plank position.',
      'Drive one knee toward your chest.',
      'Switch legs while keeping your hips steady.',
    ],
  },
]
