export const workoutPlanStorageKey = 'fitness-flow-workout-plan'

export const exercises = [
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    group: 'Legs',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 8,
    description: 'A simple leg exercise that works your quads and glutes.',
    steps: [
      'Stand with your feet shoulder-width apart.',
      'Bend your knees and sit your hips back.',
      'Stand back up and squeeze your glutes.',
    ],
  },
  {
    id: 'lunge',
    name: 'Walking Lunge',
    group: 'Legs',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 10,
    description: 'A lower body move that also helps with balance.',
    steps: [
      'Step one foot forward.',
      'Lower your back knee toward the floor.',
      'Push through the front foot and switch sides.',
    ],
  },
  {
    id: 'push-up',
    name: 'Push-up',
    group: 'Chest',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 7,
    description: 'A classic upper body exercise for chest, arms, and core.',
    steps: [
      'Start in a plank with hands under shoulders.',
      'Lower your chest toward the floor.',
      'Push back up while keeping your body straight.',
    ],
  },
  {
    id: 'row',
    name: 'Dumbbell Row',
    group: 'Back',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 8,
    description: 'A back exercise that also trains your arms.',
    steps: [
      'Place one hand on a bench or chair.',
      'Pull the dumbbell toward your ribs.',
      'Lower the dumbbell slowly and switch sides.',
    ],
  },
  {
    id: 'plank',
    name: 'Front Plank',
    group: 'Core',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 5,
    description: 'A core exercise that teaches you to stay tight and steady.',
    steps: [
      'Rest on your forearms and toes.',
      'Keep your hips level with your shoulders.',
      'Hold the position while breathing normally.',
    ],
  },
  {
    id: 'curl',
    name: 'Biceps Curl',
    group: 'Arms',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 6,
    description: 'A simple arm exercise for the front of your upper arms.',
    steps: [
      'Hold dumbbells at your sides.',
      'Curl the weights toward your shoulders.',
      'Lower them slowly without swinging.',
    ],
  },
  {
    id: 'jumping-jack',
    name: 'Jumping Jack',
    group: 'Cardio',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 6,
    description: 'A quick cardio exercise to warm up the whole body.',
    steps: [
      'Stand tall with your arms at your sides.',
      'Jump your feet out and raise your arms.',
      'Jump back to the starting position.',
    ],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    group: 'Cardio',
    equipment: 'Body Weight',
    level: 'Medium',
    minutes: 7,
    description: 'A faster exercise that mixes cardio and core work.',
    steps: [
      'Start in a plank position.',
      'Drive one knee toward your chest.',
      'Switch legs while keeping your hips steady.',
    ],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    group: 'Legs',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 6,
    description: 'A simple move for glutes, hamstrings, and lower body control.',
    steps: [
      'Lie on your back with knees bent and feet flat.',
      'Push through your heels and lift your hips.',
      'Lower your hips slowly and repeat.',
    ],
  },
  {
    id: 'shoulder-press',
    name: 'Dumbbell Shoulder Press',
    group: 'Arms',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 7,
    description: 'An upper body exercise that works your shoulders and arms.',
    steps: [
      'Hold dumbbells at shoulder height.',
      'Press the weights overhead without leaning back.',
      'Lower them slowly to your shoulders.',
    ],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    group: 'Core',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 5,
    description: 'A core exercise that helps you stay steady while moving.',
    steps: [
      'Lie on your back with arms up and knees bent.',
      'Lower one arm and the opposite leg slowly.',
      'Return to the start and switch sides.',
    ],
  },
  {
    id: 'superman',
    name: 'Superman Hold',
    group: 'Back',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 5,
    description: 'A back exercise that strengthens your lower back and posture.',
    steps: [
      'Lie face down with arms stretched forward.',
      'Lift your arms, chest, and legs slightly off the floor.',
      'Hold briefly, then lower with control.',
    ],
  },
  {
    id: 'chest-press',
    name: 'Dumbbell Chest Press',
    group: 'Chest',
    equipment: 'Dumbbells',
    level: 'Beginner',
    minutes: 8,
    description: 'A chest exercise that also works your shoulders and triceps.',
    steps: [
      'Lie on a bench or the floor with dumbbells near your chest.',
      'Press the weights upward until your arms are straight.',
      'Lower the dumbbells slowly back down.',
    ],
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    group: 'Cardio',
    equipment: 'Body Weight',
    level: 'Beginner',
    minutes: 6,
    description: 'A quick cardio move that raises your heart rate.',
    steps: [
      'Stand tall with your arms bent at your sides.',
      'Run in place while lifting your knees high.',
      'Keep your chest up and move at a steady pace.',
    ],
  },
]
